on:
  workflow_dispatch:
  schedule:
    - cron:  '*/5 * * * *'

jobs:
  sync_with_upstream:
    runs-on: ubuntu-latest
    name: Sync master with upstream latest

    steps:
      # Step 1: run a standard checkout action, provided by github
      - name: Checkout master
        uses: actions/checkout@master

      # Step 2: run this sync action - specify the upstream repo, upstream branch to sync with, and target sync branch
      - name: Pull (Rebase) upstream changes
        id: sync
        uses: aormsby/Fork-Sync-With-Upstream-action@v2.1
        with:
          upstream_repository: ros/rosdistro
          upstream_branch: master
          target_branch: master
          git_pull_args: --rebase
          git_fetch_args: --tags
          github_token: ${{ secrets.GITHUB_TOKEN }}

      # Step 3: Display a message if 'sync' step had new commits (simple test)
      - name: Check for new commits
        if: steps.sync.outputs.has-new-commits
        run: echo "There were new commits."

      # Step 4: Print a helpful timestamp for your records (not required)
      - name: Timestamp
        run: date
